---
- name: Create nginx site config
  template: src=frontend.conf.j2 dest=/etc/nginx/conf.d/frontend.conf
  notify: 
   - reload nginx

- name: Pull in git of frontend
  git: repo=https://github.com/atleechurch/rtmp-frontend.git 
       dest={{ site_root }}